### ISSUE TITLE
What's the difference between this and the lib it's based on, chatto?

### ISSUE THREAD

**Issue by sirvon** [little2s/NoChat#1]
What's the difference between this and the lib it's based on, chatto?

Thanks!

**Comment by little2s** [comment]
Hi @sirvon ,

I just make a little change from Chatto, 
1. Keyboard interactive, most IM application hide the keyboard by tap the blank on messages area,
   NoChat let this UX as default, and I think handle keyboard events is the duty of input controller,
   so I remove the `KeyboardTracker`, maybe someone want to write a chat app just input stickers. 
   Less is more, I think so.
2. Invert mode, you must do something special to support a `invert` chat UI like Telegram, Slack,WhatsApp etc. Messages grow from bottom to top. And you also have to think about iOS user's habit，
   when user tap the status bar, message box should scroll to the top, etc.
3. Companion frameworks, there are three styles I provide for this framework in the Demo app, the purpose is to show that it can work with different UI or UX design.
4. Future, it's hard to say the difference in the future, I want to keep this framework lightweight and extendable, maybe provide more public API and protocols.

At that time, I rewrite this for my company's demand, now I hope this framework can help people who had the same problem. By the way, Chatto is awesome, I have learned a lot things from open source community, now I just want to do something for open source :]

Thanks for your question.
