### ISSUE TITLE
接收 / 传送图片

### ISSUE THREAD

**Issue by ji3g4m6zo6** [little2s/NoChat#19]
请问目前有支持接收 / 传送图片吗？

我将 Message 的 msgType 设为"Image"
`attachments: [MessageAttachmentProtocol]`
這個部分 attachments要如何设置呢？

谢谢您开发这么方便的套件

**Comment by little2s** [comment]
您可以创建一个ImageAttachment类来封装图片附件数据，比如图片的宽、高、URL等，注意要实现MessageAttachmentProtocol协议。看到您使用的0.3版本以前库，目前这个库做了很大的改动，建议您去阅读新的README，您可以根据您的喜好选择。@ji3g4m6zo6
