### ISSUE TITLE
Typing Indicator

### ISSUE THREAD

**Issue by mbalex99** [little2s/NoChat#2]
How do you do a typing indicator?

**Comment by little2s** [comment]
Hi @mbalex99 ,
I'm sorry for answer so late.
The typing indicator depend on UI design, for example, WeChat and Telegram just show typing status on titleView of navigationItem, Slack just add another view above the input bar to show this information.

**Comment by mbalex99** [comment]
That's what I ended up doing thank you! 谢谢！

**Comment by little2s** [comment]
You're welcome 😄 @mbalex99
