### ISSUE TITLE
IB support

### ISSUE THREAD

**Issue by krisanthony** [little2s/NoChat#20]
It looks like the implementation is tied to the use of init frame for input bar and cells. Any reason to not support IB, and plans to support it?

**Comment by little2s** [comment]
@krisanthony IB is a great tool, and developers always use IB with AutoLayout,  but they're not good for performance. I does not plan to support them. You may interest in these discussions: http://pilky.me/36/, https://github.com/facebook/AsyncDisplayKit/issues/132

**Comment by krisanthony** [comment]
This is quite outdated.. performance since has vastly improved and you'll easily find more recent articles finding ib outperforms programmatically built views. You'll notice chatto (what this is based on) uses ib and autolayout. To each their own.

**Comment by little2s** [comment]
@krisanthony yeah, chatto supports IB and autolayout, but I think it's not a good choice. You can look at TextMessageCollectionViewCell in ChattoAdditions and find out why they use manual layout. Here is also a blog which was written by the author of Chatto: http://techblog.badoo.com/blog/2015/12/04/how-we-made-chatto/

**Comment by krisanthony** [comment]
That's very interesting thanks. I understand the argument for cells. But for the input panel?

**Comment by little2s** [comment]
@krisanthony In fact, it's okay to use IB to build UI for the input panel. I just wanna to implement a function that when user resized the size class, collectionView could still scroll to the message which user saw last time just like Telegram. When I use manual layout to calculate the height of input panel before resizing, it seems much more easier than use auto layout.
