### ISSUE TITLE
Memory Leak or Retain Cycle

### ISSUE THREAD

**Issue by mbalex99** [little2s/NoChat#3]
# It looks like there's a memory leak somewhere.

If you put 

``` swift
    deinit {
        print("Deinit Called")
    }
```

It never gets called in the demo project. There's some memory leak or strong retain cycle

**Comment by little2s** [comment]
Hi @mbalex99 ,
Memory problem is so bad, could you tell me this happening on which class? And more context about it?Thank you!

**Comment by mbalex99** [comment]
It's happening in all the demo controllers

**Comment by mbalex99** [comment]
You can out deinit in all demo controllers for TG, MM and SLK and find that
deinit is not called.

**Comment by little2s** [comment]
Thanks for your feedback, there is a retain cycle between ChatViewController and ChatInputViewController, I have fixed it on this commit 141d924bc0aa2d05bdd267f2424691efd09c43df. @mbalex99

**Comment by mbalex99** [comment]
Yes thank you so much!!!

**Comment by mbalex99** [comment]
Did you push to trunk for cocoapods or should I use this git branch?

**Comment by little2s** [comment]
This issue happened on Demo project, all of the pods need not to be changed. @mbalex99

**Comment by mbalex99** [comment]
Ah I'm sorry I realized just now thank you!
