### ISSUE TITLE
Telegram example not finished

### ISSUE THREAD

**Issue by seidju** [little2s/NoChat#5]
Hello! First of all I want to thank you for such great examples of popular IM based on NoChat.
When i looked through code of NoChatTG I saw, that you implement such features as Failed delivery, clock-like sending indicator and etc. But, in Demo example all this features aren't used. Maybe you have some more newer example of this project?

**Comment by mbalex99** [comment]
You should be able to just subclass it or copy the NoChatTG examples to get this working to your specific needs. I believe these are just easy demonstrations of how NoChat works.

**Comment by little2s** [comment]
@seidju I'm sorry for answer you late. NoChat was born from a real IM project in my company. When I make it open source, some features such as failed delivery... en... I just forget to delete it... I'll fix this next version. Thank you.
