### ISSUE TITLE
messages of type image and video

### ISSUE THREAD

**Issue by anupamme** [little2s/NoChat#7]
It looks that image type is partially supported

public enum MessageType: String {
    case Text = "Text"
    case Image = "Image"
}

But in Message class type of content is String. So in case of image this string is supposed to be the address of the image and not the UIImage instance? Is that how it was designed?

And what will be the steps to add video type here? An overview would be great.

**Comment by little2s** [comment]
@anupamme sorry for answer you late. Use 'attachments' property in 'Message' class for media support.
