### ISSUE TITLE
inputbar移位问题

### ISSUE THREAD

**Issue by brycezhang** [little2s/NoChat#9]
当聊天页面作为二级页面，push需要隐藏tabbar时，inputbar会出现一个移位，如下图：
![gif image](http://lib.wuedc.com/uploadimg/uploadimg/1469098371.gif)
(markdown展示gif貌似有问题，烦请点图片链接)http://lib.wuedc.com/uploadimg/uploadimg/1469098371.gif
请问如何解决？

**Comment by little2s** [comment]
@brycezhang 很抱歉，现在才回答您的问题，上面的图片链接失效了，可以重新发一个吗？

**Comment by brycezhang** [comment]
@little2s 我重新录制了gif上传到百度盘 https://pan.baidu.com/s/1eSfrEdc
问题重现步骤：
1.将demo中的入口控制器换成UITabBarController；
2.进入聊天页面时，设置hidesBottomBarWhenPushed为true。

**Comment by little2s** [comment]
@brycezhang 我调整了ChatViewController的自动布局，代码更新到了master，同步修改了swift2_3分支。后续会将整个项目迁移到swift3。感谢您的反馈！
